### ISSUE TITLE
E-Tab 5 nerede?

### ISSUE THREAD

**Issue by tunasahinn** [general-mobile/gm9go-omr1-kernel#3]
Anladık açık kaynak seviyorsunuz Hüsne hanım ama bize de E-Tab5 lazım yani.

**Comment by brsgk** [comment]
annende etab5

**Comment by tunasahinn** [comment]
Aaa engelli yorum yapmış

**Comment by tunasahinn** [comment]
Engelliler geldiği için sorun yok
